<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GRID0Setup</AssemblyName>
    <RootNamespace>GRID0Setup</RootNamespace>
    <Version>1.0.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>grid0.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="banner.png" />
  </ItemGroup>

</Project>
